import type { ProviderConfigInput } from "@/lib/types";

export const DEFAULT_PROVIDER_CONFIGS: ProviderConfigInput[] = [
  {
    provider: "apollo",
    enabled: true,
    priority: 1,
    costPerRequest: 0.02,
    costPerSuccessfulContact: 0.05,
    dailyLimit: 20,
    monthlyLimit: 300,
  },
  {
    provider: "hunter",
    enabled: true,
    priority: 2,
    costPerRequest: 0.01,
    costPerSuccessfulContact: 0.03,
    dailyLimit: 20,
    monthlyLimit: 300,
  },
  {
    provider: "ninjapear",
    enabled: true,
    priority: 3,
    costPerRequest: 0.03,
    costPerSuccessfulContact: 0,
    dailyLimit: 20,
    monthlyLimit: 300,
  },
  {
    provider: "pdl",
    enabled: true,
    priority: 4,
    costPerRequest: 0.03,
    costPerSuccessfulContact: 0.05,
    dailyLimit: 20,
    monthlyLimit: 300,
  },
  {
    provider: "twilio",
    enabled: false,
    priority: 5,
    costPerRequest: 0.005,
    costPerSuccessfulContact: 0,
    dailyLimit: 5,
    monthlyLimit: 50,
  },
  {
    provider: "dropcontact",
    enabled: false,
    priority: 10,
    costPerRequest: 0,
    costPerSuccessfulContact: 0,
    dailyLimit: null,
    monthlyLimit: null,
  },
  {
    provider: "snov",
    enabled: false,
    priority: 11,
    costPerRequest: 0,
    costPerSuccessfulContact: 0,
    dailyLimit: null,
    monthlyLimit: null,
  },
  {
    provider: "findymail",
    enabled: false,
    priority: 12,
    costPerRequest: 0,
    costPerSuccessfulContact: 0,
    dailyLimit: null,
    monthlyLimit: null,
  },
];
